public class TrialCustomerPortalHomePageController {
   
   public List<Asset> MyRegisteredProducts {get; set;}
   public List<Case> MyRecentCases {get; set;}
   public List<Solution> TopSolutions {get; set;}
   public List<Idea> PopularIdeas {get; set;}
   
   
   public void SortProducts(){
        
    }
    public void SortCases(){
        
    }
    
    public void SortIdeas(){
        
    }
    
}